name: AWS ECR Tasks

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

jobs:
    build:
        if: github.event.pull_request.draft == false

        strategy:
            matrix:
                task: [identify, obtain, titiler]

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Docker Build Task
              run: docker build -t task-${{matrix.task}} tasks/${{matrix.task}}

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Docker Tag API
              run: docker tag task-${{matrix.task}} ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-1.amazonaws.com/raster-uploader:task-${{matrix.task}}-${{github.event.pull_request.head.sha}}

            - name: Docker Push API
              run: docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-1.amazonaws.com/raster-uploader:task-${{matrix.task}}-${{github.event.pull_request.head.sha}}
