name: Test Tasks

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

jobs:
    test:
        if: github.event.pull_request.draft == false

        strategy:
            matrix:
                task: [obtain]

        runs-on: ubuntu-latest

        timeout-minutes: 30

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Install & Test
              run: |
                cd tasks/${{matrix.task}}
                python3 -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
                python -m unittest test/*.py
